/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions.index'
import { Route as InstitutionsNursingRouteImport } from './routes/institutions.nursing'
import { Route as InstitutionsParamedicalRouteImport } from './routes/institutions.paramedical'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesProgrammeRouteImport } from './routes/programmes.$programme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsNursingRoute = InstitutionsNursingRouteImport.update({
  id: '/institutions/nursing',
  path: '/institutions/nursing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsParamedicalRoute = InstitutionsParamedicalRouteImport.update({
  id: '/institutions/paramedical',
  path: '/institutions/paramedical',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesProgrammeRoute = ProgrammesProgrammeRouteImport.update({
  id: '/programmes/$programme',
  path: '/programmes/$programme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus': typeof CampusRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/events/$slug': typeof EventsSlugRoute
  '/institutions/nursing': typeof InstitutionsNursingRoute
  '/institutions/paramedical': typeof InstitutionsParamedicalRoute
  '/programmes/$programme': typeof ProgrammesProgrammeRoute
  '/events/': typeof EventsIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus': typeof CampusRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/events/$slug': typeof EventsSlugRoute
  '/institutions/nursing': typeof InstitutionsNursingRoute
  '/institutions/paramedical': typeof InstitutionsParamedicalRoute
  '/programmes/$programme': typeof ProgrammesProgrammeRoute
  '/events': typeof EventsIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/campus': typeof CampusRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/events/$slug': typeof EventsSlugRoute
  '/institutions/nursing': typeof InstitutionsNursingRoute
  '/institutions/paramedical': typeof InstitutionsParamedicalRoute
  '/programmes/$programme': typeof ProgrammesProgrammeRoute
  '/events/': typeof EventsIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/campus'
    | '/campus-life'
    | '/contact'
    | '/gallery'
    | '/leadership'
    | '/events/$slug'
    | '/institutions/nursing'
    | '/institutions/paramedical'
    | '/programmes/$programme'
    | '/events/'
    | '/institutions/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/campus'
    | '/campus-life'
    | '/contact'
    | '/gallery'
    | '/leadership'
    | '/events/$slug'
    | '/institutions/nursing'
    | '/institutions/paramedical'
    | '/programmes/$programme'
    | '/events'
    | '/institutions'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/campus'
    | '/campus-life'
    | '/contact'
    | '/gallery'
    | '/leadership'
    | '/events/$slug'
    | '/institutions/nursing'
    | '/institutions/paramedical'
    | '/programmes/$programme'
    | '/events/'
    | '/institutions/'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusRoute: typeof CampusRoute
  CampusLifeRoute: typeof CampusLifeRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LeadershipRoute: typeof LeadershipRoute
  EventsSlugRoute: typeof EventsSlugRoute
  InstitutionsNursingRoute: typeof InstitutionsNursingRoute
  InstitutionsParamedicalRoute: typeof InstitutionsParamedicalRoute
  ProgrammesProgrammeRoute: typeof ProgrammesProgrammeRoute
  EventsIndexRoute: typeof EventsIndexRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/nursing': {
      id: '/institutions/nursing'
      path: '/institutions/nursing'
      fullPath: '/institutions/nursing'
      preLoaderRoute: typeof InstitutionsNursingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/paramedical': {
      id: '/institutions/paramedical'
      path: '/institutions/paramedical'
      fullPath: '/institutions/paramedical'
      preLoaderRoute: typeof InstitutionsParamedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$programme': {
      id: '/programmes/$programme'
      path: '/programmes/$programme'
      fullPath: '/programmes/$programme'
      preLoaderRoute: typeof ProgrammesProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusRoute: CampusRoute,
  CampusLifeRoute: CampusLifeRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LeadershipRoute: LeadershipRoute,
  EventsSlugRoute: EventsSlugRoute,
  InstitutionsNursingRoute: InstitutionsNursingRoute,
  InstitutionsParamedicalRoute: InstitutionsParamedicalRoute,
  ProgrammesProgrammeRoute: ProgrammesProgrammeRoute,
  EventsIndexRoute: EventsIndexRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
